a = float(input())
operator = str(input())
b = float(input())
if operator == "+": print(f"{a:.2f} + {b:.2f} = {(a+b):.2f}")
elif operator == "-": print(f"{a:.2f} - {b:.2f} = {(a-b):.2f}")
elif operator == "x": print(f"{a:.2f} x {b:.2f} = {(a*b):.2f}")
elif operator == "/": print(f"{a:.2f} / {b:.2f} = {(a/b):.2f}")
elif operator == "mod": print(f"{a:.2f} mod {b:.2f} = {(a%b):.2f}")
elif operator == "^": print(f"{a:.2f} ^ {b:.2f} = {(a**b):.2f}")
else: print("Unknown Command")